event:
  threadpoll:
    corePoolSize: 5
    maximumPoolSize: 10
    keepAliveTime: 30
    workQueueSize: 10

spring:
  redis:
    host: 192.168.65.138
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0